# PrefixCode and Region values are injected into the pipeline at build. Refer to CloudFormation template codebuildprojectbuild resource.
EnvTag  = "dev"
SolTag  = "demoweb"
VpcCidr = "10.123"
Az01    = "eu-west-2a"
Az02    = "eu-west-2b"
EnvCode = "dv"
PublicIP = "0.0.0.0/32"
ECRRepo = "helloworld"
ImageTag ="1.0.0"